/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;
import java.util.*;

import static java.lang.Long.MAX_VALUE;
import static java.lang.Long.MIN_VALUE;

public class App {


    public static void main(String[] args) {


        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        temp(weeklyMonthTemperatures);
        System.out.println(temp(weeklyMonthTemperatures));
        System.out.println("-------------------------------------");
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");

        String winner = tally(votes);

        System.out.println(winner + " received the most votes!");
        System.out.println("----------------------------------------------------");
    }

    public static List temp(int[][] arr){
        int  smallest=Integer.MAX_VALUE;
        int largest=Integer.MIN_VALUE;
        HashSet<Integer> set=new HashSet();

        for(int x=0;x<arr.length;x++){


            for(int i=0 ;i<arr[x].length;i++){
                if(smallest>arr[x][i]){
                    smallest = arr[x][i];
                }
                if(largest<arr[x][i]){
                    largest = arr[x][i];
                }
               set.add(arr[x][i]);
            }
        }
        System.out.println("High: "+largest);
        System.out.println("Low: "+smallest);
        List<Integer> list = new ArrayList<>(set);
        List<Integer> not_seen = new ArrayList<>();
        Collections.sort(list);

        System.out.println(list);
        for (int i =smallest;i<largest;i++){
            if(!set.contains(i)) {
                System.out.println("Never saw temperature: "+i);
                not_seen.add(i);
            }
        }
        return not_seen;
    }
    public static String tally(List list){
        int largest=Integer.MIN_VALUE;
        String winner="";
        Set<String> st = new HashSet<String>(list);
        for (String s : st){
            System.out.println(s + ": " + Collections.frequency(list, s));
        if(largest<Collections.frequency(list, s)){
            largest=Collections.frequency(list, s);
            winner =s;

        }}
        return winner;
    }


}


