/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    @DisplayName("the list should retairn the not seen elemnt")
    void someCheckforweeklyMonthTemperaturesMethode() {
        int[][] weeklyMonthTemperatures = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };
        App classUnderTest = new App();
        List<Integer> expected = new ArrayList<>();
        expected.add(63);
        expected.add(67);
        expected.add(68);
        expected.add(69);
        List<Integer> test=classUnderTest.temp(weeklyMonthTemperatures);
        assertEquals(expected, test);
        System.out.println("----------------------------------------------------------------");
    }

    @Test
    @DisplayName("the array lenth should be as the parameter we inter for how many flips")
    void someCheckfortallyMethode() {
        App classUnderTest = new App();
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Shrub");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");
        String string=classUnderTest.tally(votes);
        assertEquals("Shrub", string);
        System.out.println("----------------------------------------------------------------");
    }
}
